# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -Djavax.net.ssl.trustStore=C:/Users/binbin2007/custom-truststore.jks -Djavax.net.ssl.trustStorePassword=changeit -Dcom.sun.net.ssl.checkRevocation=false
org.gradle.parallel=true

# Java version compatibility
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false

# Fabric Properties
# check these on https://fabricmc.net/develop

# Mod Properties
mod_version=0.9.5-26.3
maven_group=nl.sniffiandros.bren.common
archives_base_name=bren

# Fabric API

minecraft_version=26.3-snapshot-1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.153.1+26.3
# Fabric API